/* This file was generated by gen_cmacchk. */

#include <stdio.h>

#define MAC_SURROUND_DC(x)	MAC_SURROUND_DC2(x)
#define MAC_SURROUND_DC2(x)	MAC_SURROUND_DC3(x)
#define MAC_SURROUND_DC3(x)	#x

static void cmacchk_printDefine(char const* s, char const* t, int mode)
{
	if (mode == 1)
		printf("\tdefine\t%s\t%s\n", s, t);
	else if (mode == 2)
		printf("\tdefine\t%s\t\"%s\"\n", s, t);
	else
		printf("\tdefine\t%s\t\n", s);
}

static void cmacchk_printUndef(char const* s)
{
	printf("\tundef \t%s\n", s);
}

int  cmacchk(void)
{
	#ifdef __SGI_STL
		cmacchk_printDefine("__SGI_STL", MAC_SURROUND_DC(__SGI_STL), 1);
	#else
		cmacchk_printUndef("__SGI_STL");
	#endif
	#ifdef _STLPORT_MAJOR
		cmacchk_printDefine("_STLPORT_MAJOR", MAC_SURROUND_DC(_STLPORT_MAJOR), 1);
	#else
		cmacchk_printUndef("_STLPORT_MAJOR");
	#endif
	#ifdef _STLPORT_MINOR
		cmacchk_printDefine("_STLPORT_MINOR", MAC_SURROUND_DC(_STLPORT_MINOR), 1);
	#else
		cmacchk_printUndef("_STLPORT_MINOR");
	#endif
	#ifdef _STLPORT_PATCHLEVEL
		cmacchk_printDefine("_STLPORT_PATCHLEVEL", MAC_SURROUND_DC(_STLPORT_PATCHLEVEL), 1);
	#else
		cmacchk_printUndef("_STLPORT_PATCHLEVEL");
	#endif
	#ifdef _STLPORT_VERSION
		cmacchk_printDefine("_STLPORT_VERSION", MAC_SURROUND_DC(_STLPORT_VERSION), 1);
	#else
		cmacchk_printUndef("_STLPORT_VERSION");
	#endif
	#ifdef __BUILDING_STLPORT
		cmacchk_printDefine("__BUILDING_STLPORT", MAC_SURROUND_DC(__BUILDING_STLPORT), 1);
	#else
		cmacchk_printUndef("__BUILDING_STLPORT");
	#endif
	#ifdef _STLP_NO_IOSTREAMS
		cmacchk_printDefine("_STLP_NO_IOSTREAMS", MAC_SURROUND_DC(_STLP_NO_IOSTREAMS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_IOSTREAMS");
	#endif
	#ifdef _STLP_DEBUG
		cmacchk_printDefine("_STLP_DEBUG", MAC_SURROUND_DC(_STLP_DEBUG), 1);
	#else
		cmacchk_printUndef("_STLP_DEBUG");
	#endif
	#ifdef _STLP_DEBUG_LEVEL
		cmacchk_printDefine("_STLP_DEBUG_LEVEL", MAC_SURROUND_DC(_STLP_DEBUG_LEVEL), 1);
	#else
		cmacchk_printUndef("_STLP_DEBUG_LEVEL");
	#endif
	#ifdef _STLP_DEBUG_MODE_THROWS
		cmacchk_printDefine("_STLP_DEBUG_MODE_THROWS", MAC_SURROUND_DC(_STLP_DEBUG_MODE_THROWS), 1);
	#else
		cmacchk_printUndef("_STLP_DEBUG_MODE_THROWS");
	#endif
	#ifdef _STLP_NO_CUSTOM_IO
		cmacchk_printDefine("_STLP_NO_CUSTOM_IO", MAC_SURROUND_DC(_STLP_NO_CUSTOM_IO), 1);
	#else
		cmacchk_printUndef("_STLP_NO_CUSTOM_IO");
	#endif
	#ifdef _STLP_NO_RELOPS_NAMESPACE
		cmacchk_printDefine("_STLP_NO_RELOPS_NAMESPACE", MAC_SURROUND_DC(_STLP_NO_RELOPS_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_NO_RELOPS_NAMESPACE");
	#endif
	#ifdef _STLP_DONT_REDEFINE_STD
		cmacchk_printDefine("_STLP_DONT_REDEFINE_STD", MAC_SURROUND_DC(_STLP_DONT_REDEFINE_STD), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_REDEFINE_STD");
	#endif
	#ifdef _STLP_WHOLE_NATIVE_STD
		cmacchk_printDefine("_STLP_WHOLE_NATIVE_STD", MAC_SURROUND_DC(_STLP_WHOLE_NATIVE_STD), 1);
	#else
		cmacchk_printUndef("_STLP_WHOLE_NATIVE_STD");
	#endif
	#ifdef _STLP_DEBUG_UNINITIALIZED
		cmacchk_printDefine("_STLP_DEBUG_UNINITIALIZED", MAC_SURROUND_DC(_STLP_DEBUG_UNINITIALIZED), 1);
	#else
		cmacchk_printUndef("_STLP_DEBUG_UNINITIALIZED");
	#endif
	#ifdef _STLP_DEBUG_ALLOC
		cmacchk_printDefine("_STLP_DEBUG_ALLOC", MAC_SURROUND_DC(_STLP_DEBUG_ALLOC), 1);
	#else
		cmacchk_printUndef("_STLP_DEBUG_ALLOC");
	#endif
	#ifdef _STLP_SHRED_BYTE
		cmacchk_printDefine("_STLP_SHRED_BYTE", MAC_SURROUND_DC(_STLP_SHRED_BYTE), 1);
	#else
		cmacchk_printUndef("_STLP_SHRED_BYTE");
	#endif
	#ifdef _STLP_GCC_USES_GNU_LD
		cmacchk_printDefine("_STLP_GCC_USES_GNU_LD", MAC_SURROUND_DC(_STLP_GCC_USES_GNU_LD), 1);
	#else
		cmacchk_printUndef("_STLP_GCC_USES_GNU_LD");
	#endif
	#ifdef _STLP_NO_ANACHRONISMS
		cmacchk_printDefine("_STLP_NO_ANACHRONISMS", MAC_SURROUND_DC(_STLP_NO_ANACHRONISMS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_ANACHRONISMS");
	#endif
	#ifdef _STLP_NO_EXTENSIONS
		cmacchk_printDefine("_STLP_NO_EXTENSIONS", MAC_SURROUND_DC(_STLP_NO_EXTENSIONS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_EXTENSIONS");
	#endif
	#ifdef _STLP_USE_MFC
		cmacchk_printDefine("_STLP_USE_MFC", MAC_SURROUND_DC(_STLP_USE_MFC), 1);
	#else
		cmacchk_printUndef("_STLP_USE_MFC");
	#endif
	#ifdef _STLP_NEW_PLATFORM_SDK
		cmacchk_printDefine("_STLP_NEW_PLATFORM_SDK", MAC_SURROUND_DC(_STLP_NEW_PLATFORM_SDK), 1);
	#else
		cmacchk_printUndef("_STLP_NEW_PLATFORM_SDK");
	#endif
	#ifdef _STLP_USING_PLATFORM_SDK_COMPILER
		cmacchk_printDefine("_STLP_USING_PLATFORM_SDK_COMPILER", MAC_SURROUND_DC(_STLP_USING_PLATFORM_SDK_COMPILER), 1);
	#else
		cmacchk_printUndef("_STLP_USING_PLATFORM_SDK_COMPILER");
	#endif
	#ifdef _STLP_DONT_USE_AUTO_LINK
		cmacchk_printDefine("_STLP_DONT_USE_AUTO_LINK", MAC_SURROUND_DC(_STLP_DONT_USE_AUTO_LINK), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_USE_AUTO_LINK");
	#endif
	#ifdef _STLP_LIB_NAME_MOTIF
		cmacchk_printDefine("_STLP_LIB_NAME_MOTIF", _STLP_LIB_NAME_MOTIF, 2);
	#else
		cmacchk_printUndef("_STLP_LIB_NAME_MOTIF");
	#endif
	#ifdef _STLP_VERBOSE
		cmacchk_printDefine("_STLP_VERBOSE", MAC_SURROUND_DC(_STLP_VERBOSE), 1);
	#else
		cmacchk_printUndef("_STLP_VERBOSE");
	#endif
	#ifdef _STLP_MINIMUM_DEFAULT_TEMPLATE_PARAMS
		cmacchk_printDefine("_STLP_MINIMUM_DEFAULT_TEMPLATE_PARAMS", MAC_SURROUND_DC(_STLP_MINIMUM_DEFAULT_TEMPLATE_PARAMS), 1);
	#else
		cmacchk_printUndef("_STLP_MINIMUM_DEFAULT_TEMPLATE_PARAMS");
	#endif
	#ifdef _STLP_USE_TEMPLATE_EXPRESSION
		cmacchk_printDefine("_STLP_USE_TEMPLATE_EXPRESSION", MAC_SURROUND_DC(_STLP_USE_TEMPLATE_EXPRESSION), 1);
	#else
		cmacchk_printUndef("_STLP_USE_TEMPLATE_EXPRESSION");
	#endif
	#ifdef _STLP_DONT_USE_SHORT_STRING_OPTIM
		cmacchk_printDefine("_STLP_DONT_USE_SHORT_STRING_OPTIM", MAC_SURROUND_DC(_STLP_DONT_USE_SHORT_STRING_OPTIM), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_USE_SHORT_STRING_OPTIM");
	#endif
	#ifdef _STLP_USE_PTR_SPECIALIZATIONS
		cmacchk_printDefine("_STLP_USE_PTR_SPECIALIZATIONS", MAC_SURROUND_DC(_STLP_USE_PTR_SPECIALIZATIONS), 1);
	#else
		cmacchk_printUndef("_STLP_USE_PTR_SPECIALIZATIONS");
	#endif
	#ifdef _STLP_USE_BOOST_SUPPORT
		cmacchk_printDefine("_STLP_USE_BOOST_SUPPORT", MAC_SURROUND_DC(_STLP_USE_BOOST_SUPPORT), 1);
	#else
		cmacchk_printUndef("_STLP_USE_BOOST_SUPPORT");
	#endif
	#ifdef _STLP_ABORT
		cmacchk_printDefine("_STLP_ABORT", MAC_SURROUND_DC(_STLP_ABORT), 1);
	#else
		cmacchk_printUndef("_STLP_ABORT");
	#endif
	#ifdef _STLP_ALLOCATOR_TYPE_DFL
		cmacchk_printDefine("_STLP_ALLOCATOR_TYPE_DFL", MAC_SURROUND_DC(_STLP_ALLOCATOR_TYPE_DFL), 1);
	#else
		cmacchk_printUndef("_STLP_ALLOCATOR_TYPE_DFL");
	#endif
	#ifdef _STLP_BASE_TYPEDEF_BUG
		cmacchk_printDefine("_STLP_BASE_TYPEDEF_BUG", MAC_SURROUND_DC(_STLP_BASE_TYPEDEF_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_BASE_TYPEDEF_BUG");
	#endif
	#ifdef _STLP_BASE_TYPEDEF_OUTSIDE_BUG
		cmacchk_printDefine("_STLP_BASE_TYPEDEF_OUTSIDE_BUG", MAC_SURROUND_DC(_STLP_BASE_TYPEDEF_OUTSIDE_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_BASE_TYPEDEF_OUTSIDE_BUG");
	#endif
	#ifdef _STLP_BIG_ENDIAN
		cmacchk_printDefine("_STLP_BIG_ENDIAN", MAC_SURROUND_DC(_STLP_BIG_ENDIAN), 1);
	#else
		cmacchk_printUndef("_STLP_BIG_ENDIAN");
	#endif
	#ifdef _STLP_BOGUS_TEMPLATE_TYPE_MATCHING_BUG
		cmacchk_printDefine("_STLP_BOGUS_TEMPLATE_TYPE_MATCHING_BUG", MAC_SURROUND_DC(_STLP_BOGUS_TEMPLATE_TYPE_MATCHING_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_BOGUS_TEMPLATE_TYPE_MATCHING_BUG");
	#endif
	#ifdef _STLP_BROKEN_USING_DIRECTIVE
		cmacchk_printDefine("_STLP_BROKEN_USING_DIRECTIVE", MAC_SURROUND_DC(_STLP_BROKEN_USING_DIRECTIVE), 1);
	#else
		cmacchk_printUndef("_STLP_BROKEN_USING_DIRECTIVE");
	#endif
	#ifdef _STLP_BOOL_KEYWORD
		cmacchk_printDefine("_STLP_BOOL_KEYWORD", MAC_SURROUND_DC(_STLP_BOOL_KEYWORD), 1);
	#else
		cmacchk_printUndef("_STLP_BOOL_KEYWORD");
	#endif
	#ifdef _STLP_CALL
		cmacchk_printDefine("_STLP_CALL", MAC_SURROUND_DC(_STLP_CALL), 1);
	#else
		cmacchk_printUndef("_STLP_CALL");
	#endif
	#ifdef _STLP_CHECK_RUNTIME_COMPATIBILITY
		cmacchk_printDefine("_STLP_CHECK_RUNTIME_COMPATIBILITY", MAC_SURROUND_DC(_STLP_CHECK_RUNTIME_COMPATIBILITY), 1);
	#else
		cmacchk_printUndef("_STLP_CHECK_RUNTIME_COMPATIBILITY");
	#endif
	#ifdef _STLP_CLASS_EXPORT_DECLSPEC
		cmacchk_printDefine("_STLP_CLASS_EXPORT_DECLSPEC", MAC_SURROUND_DC(_STLP_CLASS_EXPORT_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_CLASS_EXPORT_DECLSPEC");
	#endif
	#ifdef _STLP_CLASS_IMPORT_DECLSPEC
		cmacchk_printDefine("_STLP_CLASS_IMPORT_DECLSPEC", MAC_SURROUND_DC(_STLP_CLASS_IMPORT_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_CLASS_IMPORT_DECLSPEC");
	#endif
	#ifdef _STLP_CLASS_PARTIAL_SPECIALIZATION
		cmacchk_printDefine("_STLP_CLASS_PARTIAL_SPECIALIZATION", MAC_SURROUND_DC(_STLP_CLASS_PARTIAL_SPECIALIZATION), 1);
	#else
		cmacchk_printUndef("_STLP_CLASS_PARTIAL_SPECIALIZATION");
	#endif
	#ifdef _STLP_DEFAULT_TYPE_PARAM
		cmacchk_printDefine("_STLP_DEFAULT_TYPE_PARAM", MAC_SURROUND_DC(_STLP_DEFAULT_TYPE_PARAM), 1);
	#else
		cmacchk_printUndef("_STLP_DEFAULT_TYPE_PARAM");
	#endif
	#ifdef _STLP_DEF_CONST_DEF_PARAM_BUG
		cmacchk_printDefine("_STLP_DEF_CONST_DEF_PARAM_BUG", MAC_SURROUND_DC(_STLP_DEF_CONST_DEF_PARAM_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_DEF_CONST_DEF_PARAM_BUG");
	#endif
	#ifdef _STLP_DESIGNATED_DLL
		cmacchk_printDefine("_STLP_DESIGNATED_DLL", MAC_SURROUND_DC(_STLP_DESIGNATED_DLL), 1);
	#else
		cmacchk_printUndef("_STLP_DESIGNATED_DLL");
	#endif
	#ifdef _STLP_DLLEXPORT_NEEDS_PREDECLARATION
		cmacchk_printDefine("_STLP_DLLEXPORT_NEEDS_PREDECLARATION", MAC_SURROUND_DC(_STLP_DLLEXPORT_NEEDS_PREDECLARATION), 1);
	#else
		cmacchk_printUndef("_STLP_DLLEXPORT_NEEDS_PREDECLARATION");
	#endif
	#ifdef _STLP_DONT_SIMULATE_PARTIAL_SPEC_FOR_TYPE_TRAITS
		cmacchk_printDefine("_STLP_DONT_SIMULATE_PARTIAL_SPEC_FOR_TYPE_TRAITS", MAC_SURROUND_DC(_STLP_DONT_SIMULATE_PARTIAL_SPEC_FOR_TYPE_TRAITS), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_SIMULATE_PARTIAL_SPEC_FOR_TYPE_TRAITS");
	#endif
	#ifdef _STLP_DONT_SUPPORT_REBIND_MEMBER_TEMPLATE
		cmacchk_printDefine("_STLP_DONT_SUPPORT_REBIND_MEMBER_TEMPLATE", MAC_SURROUND_DC(_STLP_DONT_SUPPORT_REBIND_MEMBER_TEMPLATE), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_SUPPORT_REBIND_MEMBER_TEMPLATE");
	#endif
	#ifdef _STLP_DONT_SUP_DFLT_PARAM
		cmacchk_printDefine("_STLP_DONT_SUP_DFLT_PARAM", MAC_SURROUND_DC(_STLP_DONT_SUP_DFLT_PARAM), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_SUP_DFLT_PARAM");
	#endif
	#ifdef _STLP_DONT_USE_BOOL_TYPEDEF
		cmacchk_printDefine("_STLP_DONT_USE_BOOL_TYPEDEF", MAC_SURROUND_DC(_STLP_DONT_USE_BOOL_TYPEDEF), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_USE_BOOL_TYPEDEF");
	#endif
	#ifdef _STLP_DONT_USE_EXCEPTIONS
		cmacchk_printDefine("_STLP_DONT_USE_EXCEPTIONS", MAC_SURROUND_DC(_STLP_DONT_USE_EXCEPTIONS), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_USE_EXCEPTIONS");
	#endif
	#ifdef _STLP_DONT_USE_PARTIAL_SPEC_WRKD
		cmacchk_printDefine("_STLP_DONT_USE_PARTIAL_SPEC_WRKD", MAC_SURROUND_DC(_STLP_DONT_USE_PARTIAL_SPEC_WRKD), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_USE_PARTIAL_SPEC_WRKD");
	#endif
	#ifdef _STLP_DONT_USE_PRIV_NAMESPACE
		cmacchk_printDefine("_STLP_DONT_USE_PRIV_NAMESPACE", MAC_SURROUND_DC(_STLP_DONT_USE_PRIV_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_DONT_USE_PRIV_NAMESPACE");
	#endif
	#ifdef _STLP_DO_IMPORT_CSTD_FUNCTIONS
		cmacchk_printDefine("_STLP_DO_IMPORT_CSTD_FUNCTIONS", MAC_SURROUND_DC(_STLP_DO_IMPORT_CSTD_FUNCTIONS), 1);
	#else
		cmacchk_printUndef("_STLP_DO_IMPORT_CSTD_FUNCTIONS");
	#endif
	#ifdef _STLP_EXPORT_DECLSPEC
		cmacchk_printDefine("_STLP_EXPORT_DECLSPEC", MAC_SURROUND_DC(_STLP_EXPORT_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_EXPORT_DECLSPEC");
	#endif
	#ifdef _STLP_EXPORT_TEMPLATE
		cmacchk_printDefine("_STLP_EXPORT_TEMPLATE", MAC_SURROUND_DC(_STLP_EXPORT_TEMPLATE), 1);
	#else
		cmacchk_printUndef("_STLP_EXPORT_TEMPLATE");
	#endif
	#ifdef _STLP_EXPORT_TEMPLATE_KEYWORD
		cmacchk_printDefine("_STLP_EXPORT_TEMPLATE_KEYWORD", MAC_SURROUND_DC(_STLP_EXPORT_TEMPLATE_KEYWORD), 1);
	#else
		cmacchk_printUndef("_STLP_EXPORT_TEMPLATE_KEYWORD");
	#endif
	#ifdef _STLP_FUNCTION_TMPL_PARTIAL_ORDER
		cmacchk_printDefine("_STLP_FUNCTION_TMPL_PARTIAL_ORDER", MAC_SURROUND_DC(_STLP_FUNCTION_TMPL_PARTIAL_ORDER), 1);
	#else
		cmacchk_printUndef("_STLP_FUNCTION_TMPL_PARTIAL_ORDER");
	#endif
	#ifdef _STLP_HAS_INCLUDE_NEXT
		cmacchk_printDefine("_STLP_HAS_INCLUDE_NEXT", MAC_SURROUND_DC(_STLP_HAS_INCLUDE_NEXT), 1);
	#else
		cmacchk_printUndef("_STLP_HAS_INCLUDE_NEXT");
	#endif
	#ifdef _STLP_HAS_NO_EXCEPTIONS
		cmacchk_printDefine("_STLP_HAS_NO_EXCEPTIONS", MAC_SURROUND_DC(_STLP_HAS_NO_EXCEPTIONS), 1);
	#else
		cmacchk_printUndef("_STLP_HAS_NO_EXCEPTIONS");
	#endif
	#ifdef _STLP_HAS_NO_NAMESPACES
		cmacchk_printDefine("_STLP_HAS_NO_NAMESPACES", MAC_SURROUND_DC(_STLP_HAS_NO_NAMESPACES), 1);
	#else
		cmacchk_printUndef("_STLP_HAS_NO_NAMESPACES");
	#endif
	#ifdef _STLP_HAS_NO_NEW_C_HEADERS
		cmacchk_printDefine("_STLP_HAS_NO_NEW_C_HEADERS", MAC_SURROUND_DC(_STLP_HAS_NO_NEW_C_HEADERS), 1);
	#else
		cmacchk_printUndef("_STLP_HAS_NO_NEW_C_HEADERS");
	#endif
	#ifdef _STLP_IMPORT_DECLSPEC
		cmacchk_printDefine("_STLP_IMPORT_DECLSPEC", MAC_SURROUND_DC(_STLP_IMPORT_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_IMPORT_DECLSPEC");
	#endif
	#ifdef _STLP_IMPORT_TEMPLATE_KEYWORD
		cmacchk_printDefine("_STLP_IMPORT_TEMPLATE_KEYWORD", MAC_SURROUND_DC(_STLP_IMPORT_TEMPLATE_KEYWORD), 1);
	#else
		cmacchk_printUndef("_STLP_IMPORT_TEMPLATE_KEYWORD");
	#endif
	#ifdef _STLP_INLINE_STRING_LITERAL_BUG
		cmacchk_printDefine("_STLP_INLINE_STRING_LITERAL_BUG", MAC_SURROUND_DC(_STLP_INLINE_STRING_LITERAL_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_INLINE_STRING_LITERAL_BUG");
	#endif
	#ifdef _STLP_LIMITED_DEFAULT_TEMPLATES
		cmacchk_printDefine("_STLP_LIMITED_DEFAULT_TEMPLATES", MAC_SURROUND_DC(_STLP_LIMITED_DEFAULT_TEMPLATES), 1);
	#else
		cmacchk_printUndef("_STLP_LIMITED_DEFAULT_TEMPLATES");
	#endif
	#ifdef _STLP_LITTLE_ENDIAN
		cmacchk_printDefine("_STLP_LITTLE_ENDIAN", MAC_SURROUND_DC(_STLP_LITTLE_ENDIAN), 1);
	#else
		cmacchk_printUndef("_STLP_LITTLE_ENDIAN");
	#endif
	#ifdef _STLP_LOOP_INLINE_PROBLEMS
		cmacchk_printDefine("_STLP_LOOP_INLINE_PROBLEMS", MAC_SURROUND_DC(_STLP_LOOP_INLINE_PROBLEMS), 1);
	#else
		cmacchk_printUndef("_STLP_LOOP_INLINE_PROBLEMS");
	#endif
	#ifdef _STLP_MARK_PARAMETER_AS_UNUSED
		cmacchk_printDefine("_STLP_MARK_PARAMETER_AS_UNUSED", MAC_SURROUND_DC(_STLP_MARK_PARAMETER_AS_UNUSED), 1);
	#else
		cmacchk_printUndef("_STLP_MARK_PARAMETER_AS_UNUSED");
	#endif
	#ifdef _STLP_MEMBER_TEMPLATES
		cmacchk_printDefine("_STLP_MEMBER_TEMPLATES", MAC_SURROUND_DC(_STLP_MEMBER_TEMPLATES), 1);
	#else
		cmacchk_printUndef("_STLP_MEMBER_TEMPLATES");
	#endif
	#ifdef _STLP_MEMBER_TEMPLATE_CLASSES
		cmacchk_printDefine("_STLP_MEMBER_TEMPLATE_CLASSES", MAC_SURROUND_DC(_STLP_MEMBER_TEMPLATE_CLASSES), 1);
	#else
		cmacchk_printUndef("_STLP_MEMBER_TEMPLATE_CLASSES");
	#endif
	#ifdef _STLP_MPWFIX_CATCH
		cmacchk_printDefine("_STLP_MPWFIX_CATCH", MAC_SURROUND_DC(_STLP_MPWFIX_CATCH), 1);
	#else
		cmacchk_printUndef("_STLP_MPWFIX_CATCH");
	#endif
	#ifdef _STLP_MPWFIX_CATCH_ACTION
		cmacchk_printDefine("_STLP_MPWFIX_CATCH_ACTION", MAC_SURROUND_DC(_STLP_MPWFIX_CATCH_ACTION), 1);
	#else
		cmacchk_printUndef("_STLP_MPWFIX_CATCH_ACTION");
	#endif
	#ifdef _STLP_MPWFIX_TRY
		cmacchk_printDefine("_STLP_MPWFIX_TRY", MAC_SURROUND_DC(_STLP_MPWFIX_TRY), 1);
	#else
		cmacchk_printUndef("_STLP_MPWFIX_TRY");
	#endif
	#ifdef _STLP_MSVC50_COMPATIBILITY
		cmacchk_printDefine("_STLP_MSVC50_COMPATIBILITY", MAC_SURROUND_DC(_STLP_MSVC50_COMPATIBILITY), 1);
	#else
		cmacchk_printUndef("_STLP_MSVC50_COMPATIBILITY");
	#endif
	#ifdef _STLP_NEEDS_EXTRA_TEMPLATE_CONSTRUCTORS
		cmacchk_printDefine("_STLP_NEEDS_EXTRA_TEMPLATE_CONSTRUCTORS", MAC_SURROUND_DC(_STLP_NEEDS_EXTRA_TEMPLATE_CONSTRUCTORS), 1);
	#else
		cmacchk_printUndef("_STLP_NEEDS_EXTRA_TEMPLATE_CONSTRUCTORS");
	#endif
	#ifdef _STLP_NEED_ADDITIONAL_STATIC_DECLSPEC
		cmacchk_printDefine("_STLP_NEED_ADDITIONAL_STATIC_DECLSPEC", MAC_SURROUND_DC(_STLP_NEED_ADDITIONAL_STATIC_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_NEED_ADDITIONAL_STATIC_DECLSPEC");
	#endif
	#ifdef _STLP_NEED_EXPLICIT
		cmacchk_printDefine("_STLP_NEED_EXPLICIT", MAC_SURROUND_DC(_STLP_NEED_EXPLICIT), 1);
	#else
		cmacchk_printUndef("_STLP_NEED_EXPLICIT");
	#endif
	#ifdef _STLP_NEED_MUTABLE
		cmacchk_printDefine("_STLP_NEED_MUTABLE", MAC_SURROUND_DC(_STLP_NEED_MUTABLE), 1);
	#else
		cmacchk_printUndef("_STLP_NEED_MUTABLE");
	#endif
	#ifdef _STLP_NEED_TYPENAME
		cmacchk_printDefine("_STLP_NEED_TYPENAME", MAC_SURROUND_DC(_STLP_NEED_TYPENAME), 1);
	#else
		cmacchk_printUndef("_STLP_NEED_TYPENAME");
	#endif
	#ifdef _STLP_NESTED_TYPE_PARAM_BUG
		cmacchk_printDefine("_STLP_NESTED_TYPE_PARAM_BUG", MAC_SURROUND_DC(_STLP_NESTED_TYPE_PARAM_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_NESTED_TYPE_PARAM_BUG");
	#endif
	#ifdef _STLP_NON_TYPE_TMPL_PARAM_BUG
		cmacchk_printDefine("_STLP_NON_TYPE_TMPL_PARAM_BUG", MAC_SURROUND_DC(_STLP_NON_TYPE_TMPL_PARAM_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_NON_TYPE_TMPL_PARAM_BUG");
	#endif
	#ifdef _STLP_NORETURN_FUNCTION
		cmacchk_printDefine("_STLP_NORETURN_FUNCTION", MAC_SURROUND_DC(_STLP_NORETURN_FUNCTION), 1);
	#else
		cmacchk_printUndef("_STLP_NORETURN_FUNCTION");
	#endif
	#ifdef _STLP_NOTHROW
		cmacchk_printDefine("_STLP_NOTHROW", MAC_SURROUND_DC(_STLP_NOTHROW), 1);
	#else
		cmacchk_printUndef("_STLP_NOTHROW");
	#endif
	#ifdef _STLP_NO_ARROW_OPERATOR
		cmacchk_printDefine("_STLP_NO_ARROW_OPERATOR", MAC_SURROUND_DC(_STLP_NO_ARROW_OPERATOR), 1);
	#else
		cmacchk_printUndef("_STLP_NO_ARROW_OPERATOR");
	#endif
	#ifdef _STLP_NO_AT_MEMBER_FUNCTION
		cmacchk_printDefine("_STLP_NO_AT_MEMBER_FUNCTION", MAC_SURROUND_DC(_STLP_NO_AT_MEMBER_FUNCTION), 1);
	#else
		cmacchk_printUndef("_STLP_NO_AT_MEMBER_FUNCTION");
	#endif
	#ifdef _STLP_NO_BOOL
		cmacchk_printDefine("_STLP_NO_BOOL", MAC_SURROUND_DC(_STLP_NO_BOOL), 1);
	#else
		cmacchk_printUndef("_STLP_NO_BOOL");
	#endif
	#ifdef _STLP_NO_CLASS_PARTIAL_SPECIALIZATION
		cmacchk_printDefine("_STLP_NO_CLASS_PARTIAL_SPECIALIZATION", MAC_SURROUND_DC(_STLP_NO_CLASS_PARTIAL_SPECIALIZATION), 1);
	#else
		cmacchk_printUndef("_STLP_NO_CLASS_PARTIAL_SPECIALIZATION");
	#endif
	#ifdef _STLP_NO_CONST_IN_PAIR
		cmacchk_printDefine("_STLP_NO_CONST_IN_PAIR", MAC_SURROUND_DC(_STLP_NO_CONST_IN_PAIR), 1);
	#else
		cmacchk_printUndef("_STLP_NO_CONST_IN_PAIR");
	#endif
	#ifdef _STLP_NO_EXCEPTIONS
		cmacchk_printDefine("_STLP_NO_EXCEPTIONS", MAC_SURROUND_DC(_STLP_NO_EXCEPTIONS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_EXCEPTIONS");
	#endif
	#ifdef _STLP_NO_EXCEPTION_SPEC
		cmacchk_printDefine("_STLP_NO_EXCEPTION_SPEC", MAC_SURROUND_DC(_STLP_NO_EXCEPTION_SPEC), 1);
	#else
		cmacchk_printUndef("_STLP_NO_EXCEPTION_SPEC");
	#endif
	#ifdef _STLP_NO_EXPLICIT_FUNCTION_TMPL_ARGS
		cmacchk_printDefine("_STLP_NO_EXPLICIT_FUNCTION_TMPL_ARGS", MAC_SURROUND_DC(_STLP_NO_EXPLICIT_FUNCTION_TMPL_ARGS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_EXPLICIT_FUNCTION_TMPL_ARGS");
	#endif
	#ifdef _STLP_NO_FORCE_INSTANTIATE
		cmacchk_printDefine("_STLP_NO_FORCE_INSTANTIATE", MAC_SURROUND_DC(_STLP_NO_FORCE_INSTANTIATE), 1);
	#else
		cmacchk_printUndef("_STLP_NO_FORCE_INSTANTIATE");
	#endif
	#ifdef _STLP_NO_FUNCTION_TMPL_PARTIAL_ORDER
		cmacchk_printDefine("_STLP_NO_FUNCTION_TMPL_PARTIAL_ORDER", MAC_SURROUND_DC(_STLP_NO_FUNCTION_TMPL_PARTIAL_ORDER), 1);
	#else
		cmacchk_printUndef("_STLP_NO_FUNCTION_TMPL_PARTIAL_ORDER");
	#endif
	#ifdef _STLP_NO_LONG_DOUBLE
		cmacchk_printDefine("_STLP_NO_LONG_DOUBLE", MAC_SURROUND_DC(_STLP_NO_LONG_DOUBLE), 1);
	#else
		cmacchk_printUndef("_STLP_NO_LONG_DOUBLE");
	#endif
	#ifdef _STLP_NO_MEMBER_TEMPLATES
		cmacchk_printDefine("_STLP_NO_MEMBER_TEMPLATES", MAC_SURROUND_DC(_STLP_NO_MEMBER_TEMPLATES), 1);
	#else
		cmacchk_printUndef("_STLP_NO_MEMBER_TEMPLATES");
	#endif
	#ifdef _STLP_NO_MEMBER_TEMPLATE_CLASSES
		cmacchk_printDefine("_STLP_NO_MEMBER_TEMPLATE_CLASSES", MAC_SURROUND_DC(_STLP_NO_MEMBER_TEMPLATE_CLASSES), 1);
	#else
		cmacchk_printUndef("_STLP_NO_MEMBER_TEMPLATE_CLASSES");
	#endif
	#ifdef _STLP_NO_MEMBER_TEMPLATE_KEYWORD
		cmacchk_printDefine("_STLP_NO_MEMBER_TEMPLATE_KEYWORD", MAC_SURROUND_DC(_STLP_NO_MEMBER_TEMPLATE_KEYWORD), 1);
	#else
		cmacchk_printUndef("_STLP_NO_MEMBER_TEMPLATE_KEYWORD");
	#endif
	#ifdef _STLP_NO_NAMESPACES
		cmacchk_printDefine("_STLP_NO_NAMESPACES", MAC_SURROUND_DC(_STLP_NO_NAMESPACES), 1);
	#else
		cmacchk_printUndef("_STLP_NO_NAMESPACES");
	#endif
	#ifdef _STLP_NO_NATIVE_WIDE_STREAMS
		cmacchk_printDefine("_STLP_NO_NATIVE_WIDE_STREAMS", MAC_SURROUND_DC(_STLP_NO_NATIVE_WIDE_STREAMS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_NATIVE_WIDE_STREAMS");
	#endif
	#ifdef _STLP_NO_NEW_C_HEADERS
		cmacchk_printDefine("_STLP_NO_NEW_C_HEADERS", MAC_SURROUND_DC(_STLP_NO_NEW_C_HEADERS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_NEW_C_HEADERS");
	#endif
	#ifdef _STLP_NO_NEW_STYLE_CASTS
		cmacchk_printDefine("_STLP_NO_NEW_STYLE_CASTS", MAC_SURROUND_DC(_STLP_NO_NEW_STYLE_CASTS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_NEW_STYLE_CASTS");
	#endif
	#ifdef _STLP_NO_OWN_NAMESPACE
		cmacchk_printDefine("_STLP_NO_OWN_NAMESPACE", MAC_SURROUND_DC(_STLP_NO_OWN_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_NO_OWN_NAMESPACE");
	#endif
	#ifdef _STLP_NO_PARTIAL_SPECIALIZATION_SYNTAX
		cmacchk_printDefine("_STLP_NO_PARTIAL_SPECIALIZATION_SYNTAX", MAC_SURROUND_DC(_STLP_NO_PARTIAL_SPECIALIZATION_SYNTAX), 1);
	#else
		cmacchk_printUndef("_STLP_NO_PARTIAL_SPECIALIZATION_SYNTAX");
	#endif
	#ifdef _STLP_NO_SIGNED_BUILTINS
		cmacchk_printDefine("_STLP_NO_SIGNED_BUILTINS", MAC_SURROUND_DC(_STLP_NO_SIGNED_BUILTINS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_SIGNED_BUILTINS");
	#endif
	#ifdef _STLP_NO_TYPENAME_BEFORE_NAMESPACE
		cmacchk_printDefine("_STLP_NO_TYPENAME_BEFORE_NAMESPACE", MAC_SURROUND_DC(_STLP_NO_TYPENAME_BEFORE_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_NO_TYPENAME_BEFORE_NAMESPACE");
	#endif
	#ifdef _STLP_NO_TYPENAME_IN_TEMPLATE_HEADER
		cmacchk_printDefine("_STLP_NO_TYPENAME_IN_TEMPLATE_HEADER", MAC_SURROUND_DC(_STLP_NO_TYPENAME_IN_TEMPLATE_HEADER), 1);
	#else
		cmacchk_printUndef("_STLP_NO_TYPENAME_IN_TEMPLATE_HEADER");
	#endif
	#ifdef _STLP_NO_TYPENAME_ON_RETURN_TYPE
		cmacchk_printDefine("_STLP_NO_TYPENAME_ON_RETURN_TYPE", MAC_SURROUND_DC(_STLP_NO_TYPENAME_ON_RETURN_TYPE), 1);
	#else
		cmacchk_printUndef("_STLP_NO_TYPENAME_ON_RETURN_TYPE");
	#endif
	#ifdef _STLP_NO_USING_FOR_GLOBAL_FUNCTIONS
		cmacchk_printDefine("_STLP_NO_USING_FOR_GLOBAL_FUNCTIONS", MAC_SURROUND_DC(_STLP_NO_USING_FOR_GLOBAL_FUNCTIONS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_USING_FOR_GLOBAL_FUNCTIONS");
	#endif
	#ifdef _STLP_NO_WCHAR_T
		cmacchk_printDefine("_STLP_NO_WCHAR_T", MAC_SURROUND_DC(_STLP_NO_WCHAR_T), 1);
	#else
		cmacchk_printUndef("_STLP_NO_WCHAR_T");
	#endif
	#ifdef _STLP_PARTIAL_SPEC_NEEDS_TEMPLATE_ARGS
		cmacchk_printDefine("_STLP_PARTIAL_SPEC_NEEDS_TEMPLATE_ARGS", MAC_SURROUND_DC(_STLP_PARTIAL_SPEC_NEEDS_TEMPLATE_ARGS), 1);
	#else
		cmacchk_printUndef("_STLP_PARTIAL_SPEC_NEEDS_TEMPLATE_ARGS");
	#endif
	#ifdef _STLP_PRIV
		cmacchk_printDefine("_STLP_PRIV", MAC_SURROUND_DC(_STLP_PRIV), 1);
	#else
		cmacchk_printUndef("_STLP_PRIV");
	#endif
	#ifdef _STLP_PTHREADS
		cmacchk_printDefine("_STLP_PTHREADS", MAC_SURROUND_DC(_STLP_PTHREADS), 1);
	#else
		cmacchk_printUndef("_STLP_PTHREADS");
	#endif
	#ifdef _STLP_RAND48
		cmacchk_printDefine("_STLP_RAND48", MAC_SURROUND_DC(_STLP_RAND48), 1);
	#else
		cmacchk_printUndef("_STLP_RAND48");
	#endif
	#ifdef _STLP_SIMULATE_PARTIAL_SPEC_FOR_TYPE_TRAITS
		cmacchk_printDefine("_STLP_SIMULATE_PARTIAL_SPEC_FOR_TYPE_TRAITS", MAC_SURROUND_DC(_STLP_SIMULATE_PARTIAL_SPEC_FOR_TYPE_TRAITS), 1);
	#else
		cmacchk_printUndef("_STLP_SIMULATE_PARTIAL_SPEC_FOR_TYPE_TRAITS");
	#endif
	#ifdef _STLP_STATIC_ASSERT
		cmacchk_printDefine("_STLP_STATIC_ASSERT", MAC_SURROUND_DC(_STLP_STATIC_ASSERT), 1);
	#else
		cmacchk_printUndef("_STLP_STATIC_ASSERT");
	#endif
	#ifdef _STLP_STATIC_CONST_INIT_BUG
		cmacchk_printDefine("_STLP_STATIC_CONST_INIT_BUG", MAC_SURROUND_DC(_STLP_STATIC_CONST_INIT_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_STATIC_CONST_INIT_BUG");
	#endif
	#ifdef _STLP_STATIC_MUTEX
		cmacchk_printDefine("_STLP_STATIC_MUTEX", MAC_SURROUND_DC(_STLP_STATIC_MUTEX), 1);
	#else
		cmacchk_printUndef("_STLP_STATIC_MUTEX");
	#endif
	#ifdef _STLP_STD_NAME
		cmacchk_printDefine("_STLP_STD_NAME", MAC_SURROUND_DC(_STLP_STD_NAME), 1);
	#else
		cmacchk_printUndef("_STLP_STD_NAME");
	#endif
	#ifdef _STLP_THREADS
		cmacchk_printDefine("_STLP_THREADS", MAC_SURROUND_DC(_STLP_THREADS), 1);
	#else
		cmacchk_printUndef("_STLP_THREADS");
	#endif
	#ifdef _STLP_THREADS_DEFINED
		cmacchk_printDefine("_STLP_THREADS_DEFINED", MAC_SURROUND_DC(_STLP_THREADS_DEFINED), 1);
	#else
		cmacchk_printUndef("_STLP_THREADS_DEFINED");
	#endif
	#ifdef _STLP_THROW
		cmacchk_printDefine("_STLP_THROW", MAC_SURROUND_DC(_STLP_THROW), 1);
	#else
		cmacchk_printUndef("_STLP_THROW");
	#endif
	#ifdef _STLP_THROWS
		cmacchk_printDefine("_STLP_THROWS", MAC_SURROUND_DC(_STLP_THROWS), 1);
	#else
		cmacchk_printUndef("_STLP_THROWS");
	#endif
	#ifdef _STLP_THROW_RETURN_BUG
		cmacchk_printDefine("_STLP_THROW_RETURN_BUG", MAC_SURROUND_DC(_STLP_THROW_RETURN_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_THROW_RETURN_BUG");
	#endif
	#ifdef _STLP_TR1
		cmacchk_printDefine("_STLP_TR1", MAC_SURROUND_DC(_STLP_TR1), 1);
	#else
		cmacchk_printUndef("_STLP_TR1");
	#endif
	#ifdef _STLP_TRIVIAL_CONSTRUCTOR_BUG
		cmacchk_printDefine("_STLP_TRIVIAL_CONSTRUCTOR_BUG", MAC_SURROUND_DC(_STLP_TRIVIAL_CONSTRUCTOR_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_TRIVIAL_CONSTRUCTOR_BUG");
	#endif
	#ifdef _STLP_TRIVIAL_DESTRUCTOR_BUG
		cmacchk_printDefine("_STLP_TRIVIAL_DESTRUCTOR_BUG", MAC_SURROUND_DC(_STLP_TRIVIAL_DESTRUCTOR_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_TRIVIAL_DESTRUCTOR_BUG");
	#endif
	#ifdef _STLP_UINT32_T
		cmacchk_printDefine("_STLP_UINT32_T", MAC_SURROUND_DC(_STLP_UINT32_T), 1);
	#else
		cmacchk_printUndef("_STLP_UINT32_T");
	#endif
	#ifdef _STLP_USE_ABBREVS
		cmacchk_printDefine("_STLP_USE_ABBREVS", MAC_SURROUND_DC(_STLP_USE_ABBREVS), 1);
	#else
		cmacchk_printUndef("_STLP_USE_ABBREVS");
	#endif
	#ifdef _STLP_USE_CONTAINERS_EXTENSION
		cmacchk_printDefine("_STLP_USE_CONTAINERS_EXTENSION", MAC_SURROUND_DC(_STLP_USE_CONTAINERS_EXTENSION), 1);
	#else
		cmacchk_printUndef("_STLP_USE_CONTAINERS_EXTENSION");
	#endif
	#ifdef _STLP_USE_DECLSPEC
		cmacchk_printDefine("_STLP_USE_DECLSPEC", MAC_SURROUND_DC(_STLP_USE_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_USE_DECLSPEC");
	#endif
	#ifdef _STLP_USE_EXCEPTIONS
		cmacchk_printDefine("_STLP_USE_EXCEPTIONS", MAC_SURROUND_DC(_STLP_USE_EXCEPTIONS), 1);
	#else
		cmacchk_printUndef("_STLP_USE_EXCEPTIONS");
	#endif
	#ifdef _STLP_USE_MSVC6_MEM_T_BUG_WORKAROUND
		cmacchk_printDefine("_STLP_USE_MSVC6_MEM_T_BUG_WORKAROUND", MAC_SURROUND_DC(_STLP_USE_MSVC6_MEM_T_BUG_WORKAROUND), 1);
	#else
		cmacchk_printUndef("_STLP_USE_MSVC6_MEM_T_BUG_WORKAROUND");
	#endif
	#ifdef _STLP_USE_NAMESPACES
		cmacchk_printDefine("_STLP_USE_NAMESPACES", MAC_SURROUND_DC(_STLP_USE_NAMESPACES), 1);
	#else
		cmacchk_printUndef("_STLP_USE_NAMESPACES");
	#endif
	#ifdef _STLP_USE_NEW_C_HEADERS
		cmacchk_printDefine("_STLP_USE_NEW_C_HEADERS", MAC_SURROUND_DC(_STLP_USE_NEW_C_HEADERS), 1);
	#else
		cmacchk_printUndef("_STLP_USE_NEW_C_HEADERS");
	#endif
	#ifdef _STLP_USE_NO_IOSTREAMS
		cmacchk_printDefine("_STLP_USE_NO_IOSTREAMS", MAC_SURROUND_DC(_STLP_USE_NO_IOSTREAMS), 1);
	#else
		cmacchk_printUndef("_STLP_USE_NO_IOSTREAMS");
	#endif
	#ifdef _STLP_USE_OLD_HP_ITERATOR_QUERIES
		cmacchk_printDefine("_STLP_USE_OLD_HP_ITERATOR_QUERIES", MAC_SURROUND_DC(_STLP_USE_OLD_HP_ITERATOR_QUERIES), 1);
	#else
		cmacchk_printUndef("_STLP_USE_OLD_HP_ITERATOR_QUERIES");
	#endif
	#ifdef _STLP_USE_OWN_NAMESPACE
		cmacchk_printDefine("_STLP_USE_OWN_NAMESPACE", MAC_SURROUND_DC(_STLP_USE_OWN_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_USE_OWN_NAMESPACE");
	#endif
	#ifdef _STLP_USE_SEPARATE_RELOPS_NAMESPACE
		cmacchk_printDefine("_STLP_USE_SEPARATE_RELOPS_NAMESPACE", MAC_SURROUND_DC(_STLP_USE_SEPARATE_RELOPS_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_USE_SEPARATE_RELOPS_NAMESPACE");
	#endif
	#ifdef _STLP_USE_SHORT_STRING_OPTIM
		cmacchk_printDefine("_STLP_USE_SHORT_STRING_OPTIM", MAC_SURROUND_DC(_STLP_USE_SHORT_STRING_OPTIM), 1);
	#else
		cmacchk_printUndef("_STLP_USE_SHORT_STRING_OPTIM");
	#endif
	#ifdef _STLP_USE_TEMPLATE_EXPORT
		cmacchk_printDefine("_STLP_USE_TEMPLATE_EXPORT", MAC_SURROUND_DC(_STLP_USE_TEMPLATE_EXPORT), 1);
	#else
		cmacchk_printUndef("_STLP_USE_TEMPLATE_EXPORT");
	#endif
	#ifdef _STLP_USING_CROSS_NATIVE_RUNTIME_LIB
		cmacchk_printDefine("_STLP_USING_CROSS_NATIVE_RUNTIME_LIB", MAC_SURROUND_DC(_STLP_USING_CROSS_NATIVE_RUNTIME_LIB), 1);
	#else
		cmacchk_printUndef("_STLP_USING_CROSS_NATIVE_RUNTIME_LIB");
	#endif
	#ifdef _STLP_VENDOR_EXCEPT_STD
		cmacchk_printDefine("_STLP_VENDOR_EXCEPT_STD", MAC_SURROUND_DC(_STLP_VENDOR_EXCEPT_STD), 1);
	#else
		cmacchk_printUndef("_STLP_VENDOR_EXCEPT_STD");
	#endif
	#ifdef _STLP_VENDOR_GLOBAL_CSTD
		cmacchk_printDefine("_STLP_VENDOR_GLOBAL_CSTD", MAC_SURROUND_DC(_STLP_VENDOR_GLOBAL_CSTD), 1);
	#else
		cmacchk_printUndef("_STLP_VENDOR_GLOBAL_CSTD");
	#endif
	#ifdef _STLP_VENDOR_GLOBAL_EXCEPT_STD
		cmacchk_printDefine("_STLP_VENDOR_GLOBAL_EXCEPT_STD", MAC_SURROUND_DC(_STLP_VENDOR_GLOBAL_EXCEPT_STD), 1);
	#else
		cmacchk_printUndef("_STLP_VENDOR_GLOBAL_EXCEPT_STD");
	#endif
	#ifdef _STLP_VENDOR_GLOBAL_STD
		cmacchk_printDefine("_STLP_VENDOR_GLOBAL_STD", MAC_SURROUND_DC(_STLP_VENDOR_GLOBAL_STD), 1);
	#else
		cmacchk_printUndef("_STLP_VENDOR_GLOBAL_STD");
	#endif
	#ifdef _STLP_VENDOR_MB_NAMESPACE
		cmacchk_printDefine("_STLP_VENDOR_MB_NAMESPACE", MAC_SURROUND_DC(_STLP_VENDOR_MB_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_VENDOR_MB_NAMESPACE");
	#endif
	#ifdef _STLP_VERBOSE_MODE_SUPPORTED
		cmacchk_printDefine("_STLP_VERBOSE_MODE_SUPPORTED", MAC_SURROUND_DC(_STLP_VERBOSE_MODE_SUPPORTED), 1);
	#else
		cmacchk_printUndef("_STLP_VERBOSE_MODE_SUPPORTED");
	#endif
	#ifdef _STLP_WEAK
		cmacchk_printDefine("_STLP_WEAK", MAC_SURROUND_DC(_STLP_WEAK), 1);
	#else
		cmacchk_printUndef("_STLP_WEAK");
	#endif
	#ifdef _STLP_WIN32
		cmacchk_printDefine("_STLP_WIN32", MAC_SURROUND_DC(_STLP_WIN32), 1);
	#else
		cmacchk_printUndef("_STLP_WIN32");
	#endif
	#ifdef _STLP_YVALS_H
		cmacchk_printDefine("_STLP_YVALS_H", MAC_SURROUND_DC(_STLP_YVALS_H), 1);
	#else
		cmacchk_printUndef("_STLP_YVALS_H");
	#endif
	#ifdef _STLP_ARRAY_AND_SIZE
		cmacchk_printDefine("_STLP_ARRAY_AND_SIZE", MAC_SURROUND_DC(_STLP_ARRAY_AND_SIZE), 1);
	#else
		cmacchk_printUndef("_STLP_ARRAY_AND_SIZE");
	#endif
	#ifdef _STLP_ARRAY_SIZE
		cmacchk_printDefine("_STLP_ARRAY_SIZE", MAC_SURROUND_DC(_STLP_ARRAY_SIZE), 1);
	#else
		cmacchk_printUndef("_STLP_ARRAY_SIZE");
	#endif
	#ifdef _STLP_BEGIN_NAMESPACE
		cmacchk_printDefine("_STLP_BEGIN_NAMESPACE", MAC_SURROUND_DC(_STLP_BEGIN_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_BEGIN_NAMESPACE");
	#endif
	#ifdef _STLP_BEGIN_RELOPS_NAMESPACE
		cmacchk_printDefine("_STLP_BEGIN_RELOPS_NAMESPACE", MAC_SURROUND_DC(_STLP_BEGIN_RELOPS_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_BEGIN_RELOPS_NAMESPACE");
	#endif
	#ifdef _STLP_BEGIN_TR1_NAMESPACE
		cmacchk_printDefine("_STLP_BEGIN_TR1_NAMESPACE", MAC_SURROUND_DC(_STLP_BEGIN_TR1_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_BEGIN_TR1_NAMESPACE");
	#endif
	#ifdef _STLP_CAN_THROW_RANGE_ERRORS
		cmacchk_printDefine("_STLP_CAN_THROW_RANGE_ERRORS", MAC_SURROUND_DC(_STLP_CAN_THROW_RANGE_ERRORS), 1);
	#else
		cmacchk_printUndef("_STLP_CAN_THROW_RANGE_ERRORS");
	#endif
	#ifdef _STLP_CATCH_ALL
		cmacchk_printDefine("_STLP_CATCH_ALL", MAC_SURROUND_DC(_STLP_CATCH_ALL), 1);
	#else
		cmacchk_printUndef("_STLP_CATCH_ALL");
	#endif
	#ifdef _STLP_CLASS_DECLSPEC
		cmacchk_printDefine("_STLP_CLASS_DECLSPEC", MAC_SURROUND_DC(_STLP_CLASS_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_CLASS_DECLSPEC");
	#endif
	#ifdef _STLP_CONST
		cmacchk_printDefine("_STLP_CONST", MAC_SURROUND_DC(_STLP_CONST), 1);
	#else
		cmacchk_printUndef("_STLP_CONST");
	#endif
	#ifdef _STLP_DECLARE_BIDIRECTIONAL_REVERSE_ITERATORS
		cmacchk_printDefine("_STLP_DECLARE_BIDIRECTIONAL_REVERSE_ITERATORS", MAC_SURROUND_DC(_STLP_DECLARE_BIDIRECTIONAL_REVERSE_ITERATORS), 1);
	#else
		cmacchk_printUndef("_STLP_DECLARE_BIDIRECTIONAL_REVERSE_ITERATORS");
	#endif
	#ifdef _STLP_DECLARE_RANDOM_ACCESS_REVERSE_ITERATORS
		cmacchk_printDefine("_STLP_DECLARE_RANDOM_ACCESS_REVERSE_ITERATORS", MAC_SURROUND_DC(_STLP_DECLARE_RANDOM_ACCESS_REVERSE_ITERATORS), 1);
	#else
		cmacchk_printUndef("_STLP_DECLARE_RANDOM_ACCESS_REVERSE_ITERATORS");
	#endif
	#ifdef _STLP_DECLARE_REVERSE_ITERATORS
		cmacchk_printDefine("_STLP_DECLARE_REVERSE_ITERATORS", MAC_SURROUND_DC(_STLP_DECLARE_REVERSE_ITERATORS), 1);
	#else
		cmacchk_printUndef("_STLP_DECLARE_REVERSE_ITERATORS");
	#endif
	#ifdef _STLP_DECLSPEC
		cmacchk_printDefine("_STLP_DECLSPEC", MAC_SURROUND_DC(_STLP_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_DECLSPEC");
	#endif
	#ifdef _STLP_DEFAULT_PAIR_ALLOCATOR_SELECT
		cmacchk_printDefine("_STLP_DEFAULT_PAIR_ALLOCATOR_SELECT", MAC_SURROUND_DC(_STLP_DEFAULT_PAIR_ALLOCATOR_SELECT), 1);
	#else
		cmacchk_printUndef("_STLP_DEFAULT_PAIR_ALLOCATOR_SELECT");
	#endif
	#ifdef _STLP_DFL_NON_TYPE_PARAM
		cmacchk_printDefine("_STLP_DFL_NON_TYPE_PARAM", MAC_SURROUND_DC(_STLP_DFL_NON_TYPE_PARAM), 1);
	#else
		cmacchk_printUndef("_STLP_DFL_NON_TYPE_PARAM");
	#endif
	#ifdef _STLP_DFL_TMPL_PARAM
		cmacchk_printDefine("_STLP_DFL_TMPL_PARAM", MAC_SURROUND_DC(_STLP_DFL_TMPL_PARAM), 1);
	#else
		cmacchk_printUndef("_STLP_DFL_TMPL_PARAM");
	#endif
	#ifdef _STLP_DFL_TYPE_PARAM
		cmacchk_printDefine("_STLP_DFL_TYPE_PARAM", MAC_SURROUND_DC(_STLP_DFL_TYPE_PARAM), 1);
	#else
		cmacchk_printUndef("_STLP_DFL_TYPE_PARAM");
	#endif
	#ifdef _STLP_END_NAMESPACE
		cmacchk_printDefine("_STLP_END_NAMESPACE", MAC_SURROUND_DC(_STLP_END_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_END_NAMESPACE");
	#endif
	#ifdef _STLP_END_RELOPS_NAMESPACE
		cmacchk_printDefine("_STLP_END_RELOPS_NAMESPACE", MAC_SURROUND_DC(_STLP_END_RELOPS_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_END_RELOPS_NAMESPACE");
	#endif
	#ifdef _STLP_EXPORT
		cmacchk_printDefine("_STLP_EXPORT", MAC_SURROUND_DC(_STLP_EXPORT), 1);
	#else
		cmacchk_printUndef("_STLP_EXPORT");
	#endif
	#ifdef _STLP_EXPORT_TEMPLATE_CLASS
		cmacchk_printDefine("_STLP_EXPORT_TEMPLATE_CLASS", MAC_SURROUND_DC(_STLP_EXPORT_TEMPLATE_CLASS), 1);
	#else
		cmacchk_printUndef("_STLP_EXPORT_TEMPLATE_CLASS");
	#endif
	#ifdef _STLP_EXPOSE_GLOBALS_IMPLEMENTATION
		cmacchk_printDefine("_STLP_EXPOSE_GLOBALS_IMPLEMENTATION", MAC_SURROUND_DC(_STLP_EXPOSE_GLOBALS_IMPLEMENTATION), 1);
	#else
		cmacchk_printUndef("_STLP_EXPOSE_GLOBALS_IMPLEMENTATION");
	#endif
	#ifdef _STLP_EXPOSE_STREAM_IMPLEMENTATION
		cmacchk_printDefine("_STLP_EXPOSE_STREAM_IMPLEMENTATION", MAC_SURROUND_DC(_STLP_EXPOSE_STREAM_IMPLEMENTATION), 1);
	#else
		cmacchk_printUndef("_STLP_EXPOSE_STREAM_IMPLEMENTATION");
	#endif
	#ifdef _STLP_FEATURES_H
		cmacchk_printDefine("_STLP_FEATURES_H", MAC_SURROUND_DC(_STLP_FEATURES_H), 1);
	#else
		cmacchk_printUndef("_STLP_FEATURES_H");
	#endif
	#ifdef _STLP_FIX_LITERAL_BUG
		cmacchk_printDefine("_STLP_FIX_LITERAL_BUG", MAC_SURROUND_DC(_STLP_FIX_LITERAL_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_FIX_LITERAL_BUG");
	#endif
	#ifdef _STLP_FUNCTION_THROWS
		cmacchk_printDefine("_STLP_FUNCTION_THROWS", MAC_SURROUND_DC(_STLP_FUNCTION_THROWS), 1);
	#else
		cmacchk_printUndef("_STLP_FUNCTION_THROWS");
	#endif
	#ifdef _STLP_GLOBAL_NESTED_RETURN_TYPE_PARAM_BUG
		cmacchk_printDefine("_STLP_GLOBAL_NESTED_RETURN_TYPE_PARAM_BUG", MAC_SURROUND_DC(_STLP_GLOBAL_NESTED_RETURN_TYPE_PARAM_BUG), 1);
	#else
		cmacchk_printUndef("_STLP_GLOBAL_NESTED_RETURN_TYPE_PARAM_BUG");
	#endif
	#ifdef _STLP_HAS_WCHAR_T
		cmacchk_printDefine("_STLP_HAS_WCHAR_T", MAC_SURROUND_DC(_STLP_HAS_WCHAR_T), 1);
	#else
		cmacchk_printUndef("_STLP_HAS_WCHAR_T");
	#endif
	#ifdef _STLP_HEADER_TYPENAME
		cmacchk_printDefine("_STLP_HEADER_TYPENAME", MAC_SURROUND_DC(_STLP_HEADER_TYPENAME), 1);
	#else
		cmacchk_printUndef("_STLP_HEADER_TYPENAME");
	#endif
	#ifdef _STLP_IMPORT_VENDOR_CSTD
		cmacchk_printDefine("_STLP_IMPORT_VENDOR_CSTD", MAC_SURROUND_DC(_STLP_IMPORT_VENDOR_CSTD), 1);
	#else
		cmacchk_printUndef("_STLP_IMPORT_VENDOR_CSTD");
	#endif
	#ifdef _STLP_IMPORT_VENDOR_STD
		cmacchk_printDefine("_STLP_IMPORT_VENDOR_STD", MAC_SURROUND_DC(_STLP_IMPORT_VENDOR_STD), 1);
	#else
		cmacchk_printUndef("_STLP_IMPORT_VENDOR_STD");
	#endif
	#ifdef _STLP_INLINE_LOOP
		cmacchk_printDefine("_STLP_INLINE_LOOP", MAC_SURROUND_DC(_STLP_INLINE_LOOP), 1);
	#else
		cmacchk_printUndef("_STLP_INLINE_LOOP");
	#endif
	#ifdef _STLP_KEY_TYPE_FOR_CONT_EXT
		cmacchk_printDefine("_STLP_KEY_TYPE_FOR_CONT_EXT", MAC_SURROUND_DC(_STLP_KEY_TYPE_FOR_CONT_EXT), 1);
	#else
		cmacchk_printUndef("_STLP_KEY_TYPE_FOR_CONT_EXT");
	#endif
	#ifdef _STLP_LONGEST_FLOAT_TYPE
		cmacchk_printDefine("_STLP_LONGEST_FLOAT_TYPE", MAC_SURROUND_DC(_STLP_LONGEST_FLOAT_TYPE), 1);
	#else
		cmacchk_printUndef("_STLP_LONGEST_FLOAT_TYPE");
	#endif
	#ifdef _STLP_MOVE_TO_PRIV_NAMESPACE
		cmacchk_printDefine("_STLP_MOVE_TO_PRIV_NAMESPACE", MAC_SURROUND_DC(_STLP_MOVE_TO_PRIV_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_MOVE_TO_PRIV_NAMESPACE");
	#endif
	#ifdef _STLP_MOVE_TO_STD_NAMESPACE
		cmacchk_printDefine("_STLP_MOVE_TO_STD_NAMESPACE", MAC_SURROUND_DC(_STLP_MOVE_TO_STD_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_MOVE_TO_STD_NAMESPACE");
	#endif
	#ifdef _STLP_MUTABLE
		cmacchk_printDefine("_STLP_MUTABLE", MAC_SURROUND_DC(_STLP_MUTABLE), 1);
	#else
		cmacchk_printUndef("_STLP_MUTABLE");
	#endif
	#ifdef _STLP_NON_DBG_NAME
		cmacchk_printDefine("_STLP_NON_DBG_NAME", MAC_SURROUND_DC(_STLP_NON_DBG_NAME), 1);
	#else
		cmacchk_printUndef("_STLP_NON_DBG_NAME");
	#endif
	#ifdef _STLP_NOTHROW_INHERENTLY
		cmacchk_printDefine("_STLP_NOTHROW_INHERENTLY", MAC_SURROUND_DC(_STLP_NOTHROW_INHERENTLY), 1);
	#else
		cmacchk_printUndef("_STLP_NOTHROW_INHERENTLY");
	#endif
	#ifdef _STLP_NO_CSTD_FUNCTION_IMPORTS
		cmacchk_printDefine("_STLP_NO_CSTD_FUNCTION_IMPORTS", MAC_SURROUND_DC(_STLP_NO_CSTD_FUNCTION_IMPORTS), 1);
	#else
		cmacchk_printUndef("_STLP_NO_CSTD_FUNCTION_IMPORTS");
	#endif
	#ifdef _STLP_NO_DEFAULT_NON_TYPE_PARAM
		cmacchk_printDefine("_STLP_NO_DEFAULT_NON_TYPE_PARAM", MAC_SURROUND_DC(_STLP_NO_DEFAULT_NON_TYPE_PARAM), 1);
	#else
		cmacchk_printUndef("_STLP_NO_DEFAULT_NON_TYPE_PARAM");
	#endif
	#ifdef _STLP_NO_DRAND48
		cmacchk_printDefine("_STLP_NO_DRAND48", MAC_SURROUND_DC(_STLP_NO_DRAND48), 1);
	#else
		cmacchk_printUndef("_STLP_NO_DRAND48");
	#endif
	#ifdef _STLP_NO_MEM_T_NAME
		cmacchk_printDefine("_STLP_NO_MEM_T_NAME", MAC_SURROUND_DC(_STLP_NO_MEM_T_NAME), 1);
	#else
		cmacchk_printUndef("_STLP_NO_MEM_T_NAME");
	#endif
	#ifdef _STLP_NULL_TMPL_ARGS
		cmacchk_printDefine("_STLP_NULL_TMPL_ARGS", MAC_SURROUND_DC(_STLP_NULL_TMPL_ARGS), 1);
	#else
		cmacchk_printUndef("_STLP_NULL_TMPL_ARGS");
	#endif
	#ifdef _STLP_OLD_IO_NAMESPACE
		cmacchk_printDefine("_STLP_OLD_IO_NAMESPACE", MAC_SURROUND_DC(_STLP_OLD_IO_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_OLD_IO_NAMESPACE");
	#endif
	#ifdef _STLP_OPERATOR_TEMPLATE
		cmacchk_printDefine("_STLP_OPERATOR_TEMPLATE", MAC_SURROUND_DC(_STLP_OPERATOR_TEMPLATE), 1);
	#else
		cmacchk_printUndef("_STLP_OPERATOR_TEMPLATE");
	#endif
	#ifdef _STLP_PRIV_NAME
		cmacchk_printDefine("_STLP_PRIV_NAME", MAC_SURROUND_DC(_STLP_PRIV_NAME), 1);
	#else
		cmacchk_printUndef("_STLP_PRIV_NAME");
	#endif
	#ifdef _STLP_PSPEC2
		cmacchk_printDefine("_STLP_PSPEC2", MAC_SURROUND_DC(_STLP_PSPEC2), 1);
	#else
		cmacchk_printUndef("_STLP_PSPEC2");
	#endif
	#ifdef _STLP_PSPEC3
		cmacchk_printDefine("_STLP_PSPEC3", MAC_SURROUND_DC(_STLP_PSPEC3), 1);
	#else
		cmacchk_printUndef("_STLP_PSPEC3");
	#endif
	#ifdef _STLP_PTR_IMPL_NAME
		cmacchk_printDefine("_STLP_PTR_IMPL_NAME", MAC_SURROUND_DC(_STLP_PTR_IMPL_NAME), 1);
	#else
		cmacchk_printUndef("_STLP_PTR_IMPL_NAME");
	#endif
	#ifdef _STLP_RELOPS_OPERATORS
		cmacchk_printDefine("_STLP_RELOPS_OPERATORS", MAC_SURROUND_DC(_STLP_RELOPS_OPERATORS), 1);
	#else
		cmacchk_printUndef("_STLP_RELOPS_OPERATORS");
	#endif
	#ifdef _STLP_RETHROW
		cmacchk_printDefine("_STLP_RETHROW", MAC_SURROUND_DC(_STLP_RETHROW), 1);
	#else
		cmacchk_printUndef("_STLP_RETHROW");
	#endif
	#ifdef _STLP_RET_AFTER_THROW
		cmacchk_printDefine("_STLP_RET_AFTER_THROW", MAC_SURROUND_DC(_STLP_RET_AFTER_THROW), 1);
	#else
		cmacchk_printUndef("_STLP_RET_AFTER_THROW");
	#endif
	#ifdef _STLP_SIMPLE_TYPE
		cmacchk_printDefine("_STLP_SIMPLE_TYPE", MAC_SURROUND_DC(_STLP_SIMPLE_TYPE), 1);
	#else
		cmacchk_printUndef("_STLP_SIMPLE_TYPE");
	#endif
	#ifdef _STLP_STANDARD_DBG_LEVEL
		cmacchk_printDefine("_STLP_STANDARD_DBG_LEVEL", MAC_SURROUND_DC(_STLP_STANDARD_DBG_LEVEL), 1);
	#else
		cmacchk_printUndef("_STLP_STANDARD_DBG_LEVEL");
	#endif
	#ifdef _STLP_STATIC_CONSTANT
		cmacchk_printDefine("_STLP_STATIC_CONSTANT", MAC_SURROUND_DC(_STLP_STATIC_CONSTANT), 1);
	#else
		cmacchk_printUndef("_STLP_STATIC_CONSTANT");
	#endif
	#ifdef _STLP_STATIC_DECLSPEC
		cmacchk_printDefine("_STLP_STATIC_DECLSPEC", MAC_SURROUND_DC(_STLP_STATIC_DECLSPEC), 1);
	#else
		cmacchk_printUndef("_STLP_STATIC_DECLSPEC");
	#endif
	#ifdef _STLP_STD
		cmacchk_printDefine("_STLP_STD", MAC_SURROUND_DC(_STLP_STD), 1);
	#else
		cmacchk_printUndef("_STLP_STD");
	#endif
	#ifdef _STLP_STLPORT_DBG_LEVEL
		cmacchk_printDefine("_STLP_STLPORT_DBG_LEVEL", MAC_SURROUND_DC(_STLP_STLPORT_DBG_LEVEL), 1);
	#else
		cmacchk_printUndef("_STLP_STLPORT_DBG_LEVEL");
	#endif
	#ifdef _STLP_TEMPLATE
		cmacchk_printDefine("_STLP_TEMPLATE", MAC_SURROUND_DC(_STLP_TEMPLATE), 1);
	#else
		cmacchk_printUndef("_STLP_TEMPLATE");
	#endif
	#ifdef _STLP_TEMPLATE_FOR_CONT_EXT
		cmacchk_printDefine("_STLP_TEMPLATE_FOR_CONT_EXT", MAC_SURROUND_DC(_STLP_TEMPLATE_FOR_CONT_EXT), 1);
	#else
		cmacchk_printUndef("_STLP_TEMPLATE_FOR_CONT_EXT");
	#endif
	#ifdef _STLP_TEMPLATE_NULL
		cmacchk_printDefine("_STLP_TEMPLATE_NULL", MAC_SURROUND_DC(_STLP_TEMPLATE_NULL), 1);
	#else
		cmacchk_printUndef("_STLP_TEMPLATE_NULL");
	#endif
	#ifdef _STLP_THROWS_INHERENTLY
		cmacchk_printDefine("_STLP_THROWS_INHERENTLY", MAC_SURROUND_DC(_STLP_THROWS_INHERENTLY), 1);
	#else
		cmacchk_printUndef("_STLP_THROWS_INHERENTLY");
	#endif
	#ifdef _STLP_TRY
		cmacchk_printDefine("_STLP_TRY", MAC_SURROUND_DC(_STLP_TRY), 1);
	#else
		cmacchk_printUndef("_STLP_TRY");
	#endif
	#ifdef _STLP_TYPENAME
		cmacchk_printDefine("_STLP_TYPENAME", MAC_SURROUND_DC(_STLP_TYPENAME), 1);
	#else
		cmacchk_printUndef("_STLP_TYPENAME");
	#endif
	#ifdef _STLP_TYPENAME_ON_RETURN_TYPE
		cmacchk_printDefine("_STLP_TYPENAME_ON_RETURN_TYPE", MAC_SURROUND_DC(_STLP_TYPENAME_ON_RETURN_TYPE), 1);
	#else
		cmacchk_printUndef("_STLP_TYPENAME_ON_RETURN_TYPE");
	#endif
	#ifdef _STLP_UITHREADS
		cmacchk_printDefine("_STLP_UITHREADS", MAC_SURROUND_DC(_STLP_UITHREADS), 1);
	#else
		cmacchk_printUndef("_STLP_UITHREADS");
	#endif
	#ifdef _STLP_UNIX
		cmacchk_printDefine("_STLP_UNIX", MAC_SURROUND_DC(_STLP_UNIX), 1);
	#else
		cmacchk_printUndef("_STLP_UNIX");
	#endif
	#ifdef _STLP_UNWIND
		cmacchk_printDefine("_STLP_UNWIND", MAC_SURROUND_DC(_STLP_UNWIND), 1);
	#else
		cmacchk_printUndef("_STLP_UNWIND");
	#endif
	#ifdef _STLP_USE_NEWALLOC
		cmacchk_printDefine("_STLP_USE_NEWALLOC", MAC_SURROUND_DC(_STLP_USE_NEWALLOC), 1);
	#else
		cmacchk_printUndef("_STLP_USE_NEWALLOC");
	#endif
	#ifdef _STLP_USE_PARTIAL_SPEC_WORKAROUND
		cmacchk_printDefine("_STLP_USE_PARTIAL_SPEC_WORKAROUND", MAC_SURROUND_DC(_STLP_USE_PARTIAL_SPEC_WORKAROUND), 1);
	#else
		cmacchk_printUndef("_STLP_USE_PARTIAL_SPEC_WORKAROUND");
	#endif
	#ifdef _STLP_USING_NAMESPACE
		cmacchk_printDefine("_STLP_USING_NAMESPACE", MAC_SURROUND_DC(_STLP_USING_NAMESPACE), 1);
	#else
		cmacchk_printUndef("_STLP_USING_NAMESPACE");
	#endif
	#ifdef _STLP_USING_VENDOR_CSTD
		cmacchk_printDefine("_STLP_USING_VENDOR_CSTD", MAC_SURROUND_DC(_STLP_USING_VENDOR_CSTD), 1);
	#else
		cmacchk_printUndef("_STLP_USING_VENDOR_CSTD");
	#endif
	#ifdef _STLP_VENDOR_CSTD
		cmacchk_printDefine("_STLP_VENDOR_CSTD", MAC_SURROUND_DC(_STLP_VENDOR_CSTD), 1);
	#else
		cmacchk_printUndef("_STLP_VENDOR_CSTD");
	#endif
	#ifdef _STLP_VENDOR_STD
		cmacchk_printDefine("_STLP_VENDOR_STD", MAC_SURROUND_DC(_STLP_VENDOR_STD), 1);
	#else
		cmacchk_printUndef("_STLP_VENDOR_STD");
	#endif
	#ifdef _STLP_VOLATILE
		cmacchk_printDefine("_STLP_VOLATILE", MAC_SURROUND_DC(_STLP_VOLATILE), 1);
	#else
		cmacchk_printUndef("_STLP_VOLATILE");
	#endif
	#ifdef _STLP_WIN32THREADS
		cmacchk_printDefine("_STLP_WIN32THREADS", MAC_SURROUND_DC(_STLP_WIN32THREADS), 1);
	#else
		cmacchk_printUndef("_STLP_WIN32THREADS");
	#endif
	#ifdef _STLP_KKKK_USE_DMOW
		cmacchk_printDefine("_STLP_KKKK_USE_DMOW", MAC_SURROUND_DC(_STLP_KKKK_USE_DMOW), 1);
	#else
		cmacchk_printUndef("_STLP_KKKK_USE_DMOW");
	#endif
	#ifdef _STLP_KKKK_USE_LOCALE_DUMMY
		cmacchk_printDefine("_STLP_KKKK_USE_LOCALE_DUMMY", MAC_SURROUND_DC(_STLP_KKKK_USE_LOCALE_DUMMY), 1);
	#else
		cmacchk_printUndef("_STLP_KKKK_USE_LOCALE_DUMMY");
	#endif
	#ifdef _STLP_KKKK_H_INCLUDE_NEW_C_HEADERS
		cmacchk_printDefine("_STLP_KKKK_H_INCLUDE_NEW_C_HEADERS", MAC_SURROUND_DC(_STLP_KKKK_H_INCLUDE_NEW_C_HEADERS), 1);
	#else
		cmacchk_printUndef("_STLP_KKKK_H_INCLUDE_NEW_C_HEADERS");
	#endif
	return 0;
}

#if 1
int main(void)
{
	cmacchk();
	return 0;
}
#endif
